# This is a basic workflow to help you get started with Actions

name: Ansible

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: playbook.yml
          # Optional, directory where playbooks live
          directory: ./
          requirements: requirements.yml
          # Optional, literal inventory file contents
          inventory: |
            [local]
            localhost ansible_connection=local
          options: |
            --limit local
                --verbose
        env:
          SN_HOST: ${{ secrets.SN_HOST }}
          SN_USERNAME: ${{ secrets.SN_USERNAME }}
          SN_PASSWORD: ${{ secrets.SN_PASSWORD }}
          SN_CLIENT_ID: ${{ secrets.SN_CLIENT_ID }}
          SN_CLIENT_SECRET: ${{ secrets.SN_CLIENT_SECRET }}          
      - name: Run a multi-line script
        run: |
          ls -la
