# File: .github/workflows/workflow.yml

on:
  workflow_dispatch:

name: AzureCLISample

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          echo 'action_state={`az keyvault secret show --name "ExamplePassword" --vault-name "abirismyname-kv" --query "value"`}'          
          echo 'action_state={`az keyvault secret show --name "ExamplePassword" --vault-name "abirismyname-kv" --query "value"`}' >> $GITHUB_OUTPUT
    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}"           
