# This is a basic workflow to help you get started with Actions

name: Snow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Let it SNOW
        uses: shundor/servicenow-actions@main
        id: snow
        with: 
          sn_host:  "${{ secrets.SN_HOST }}"
          sn_username: "${{ secrets.SN_USERNAME }}"
          sn_password: "${{ secrets.SN_PASSWORD }}"
          sn_client_id: "${{ secrets.SN_CLIENT_ID }}"
          sn_client_secret: "${{ secrets.SN_CLIENT_SECRET }}"
          sn_module: "${{ secrets.SN_MODULE }}"
          sn_module_params: "${{ secrets.SN_MODULE_PARAMS }}"
          
      - name: Print output
        run: |
          cat ${{ steps.snow.outputs.output }} >output.txt
          cat output.txt
          exit 0
        shell: bash
